import {
  brand,
  positioning,
  levels,
  services,
  publishedCases,
  principles,
  governance,
  pruebaPropia,
  sectors,
  formatLevelRange,
  whatsappUrl,
} from "@/content"
import { SITE_URL } from "@/lib/seo"

export const dynamic = "force-static"

export function GET() {
  const lines: string[] = [
    `# ${brand.shortName}`,
    "",
    `> ${positioning.h1} ${positioning.apoyo}`,
    "",
    `${brand.shortName} es una consultora AI-native con sede en Colombia. Construye capacidades digitales que se conectan a los sistemas del cliente y ejecutan el trabajo que hoy nadie hace, organizadas en tres niveles de inversión (COP, sin IVA). La web permite probar agentes de IA reales antes de agendar una llamada.`,
    "",
    "## Sectores foco",
    "",
    ...sectors.map((s) => `- ${s}`),
    "",
    "## Niveles de inversión",
    "",
    ...levels.map((l) => `- ${l.nombre} (${formatLevelRange(l.id)}): ${l.nota}`),
    "",
    "## Servicios",
    "",
    ...services.map((s) => `- [${s.nombre}](${SITE_URL}/servicios/${s.slug}): ${s.descripcion}`),
    "",
    "## Casos",
    "",
    ...publishedCases.map(
      (c) =>
        `- [${c.titulo}](${SITE_URL}/casos/${c.slug}) (${c.sector}): ${c.resultado ? `${c.resultado.texto} ${c.resultado.encuadre}` : c.reto}`,
    ),
    "",
    "## Prueba propia",
    "",
    `${pruebaPropia.titulo}: ${pruebaPropia.texto} ${pruebaPropia.nota}`,
    "",
    "## Principios de gobernanza de IA",
    "",
    ...principles.map((p) => `- ${p.titulo}: ${p.descripcion}`),
    "",
    "## Gobernanza",
    "",
    ...governance.arquitectura.map((g) => `- ${g.termino}: ${g.beneficio}`),
    ...governance.observabilidad.map((g) => `- ${g.termino}: ${g.beneficio}`),
    "",
    "## Versión Markdown de cada página",
    "",
    `- [Inicio](${SITE_URL}/llm)`,
    `- [Servicios](${SITE_URL}/llm/servicios)`,
    `- [Casos](${SITE_URL}/llm/casos)`,
    `- [Gobernanza](${SITE_URL}/llm/gobernanza)`,
    `- [Nosotros](${SITE_URL}/llm/nosotros)`,
    `- [Preguntas](${SITE_URL}/llm/preguntas)`,
    `- [Fuerza Laboral Digital](${SITE_URL}/llm/fuerza-laboral-digital)`,
    `- La oferta completa en JSON: ${SITE_URL}/oferta.json (esquema en ${SITE_URL}/oferta.schema.json)`,
    "",
    "## Cómo contactar",
    "",
    `- Correo: ${brand.email}`,
    `- WhatsApp: ${whatsappUrl("Hola, quiero agendar un diagnóstico de 30 minutos")}`,
    `- Diagnóstico de 30 minutos, sin costo: ${SITE_URL}/#contacto`,
    "",
    "## Optional",
    "",
    `- [Formación](${SITE_URL}/formacion)`,
    `- [Recursos](${SITE_URL}/recursos)`,
    `- [Radar IA Semanal](${SITE_URL}/newsletter)`,
    `- [Aliados](${SITE_URL}/aliados)`,
    `- [Preguntas](${SITE_URL}/preguntas)`,
    `- [Nosotros](${SITE_URL}/nosotros)`,
    `- [Política de privacidad](${SITE_URL}/privacidad)`,
  ]

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  })
}
